### ISSUE TITLE
Resources don't match on hover-over

### ISSUE THREAD

**Issue by dthyne** [ldicker83/OPHD#133]
Hovering over the resources displays more details, but the rare metals and common minerals don't  match the normal display.

**Comment by ldicker83** [comment]
Interesting -- I'll look into it. Thanks for the report!

**Comment by dthyne** [comment]
I swapped lines 114 and 117 of ResourceBreakdownPanel.cpp in my local repo and it appears correctly now.

**Comment by dthyne** [comment]
However, now when I look at a factory's cost for items, the readout doesn't match the order of the ResourceBreakdownPanel.

**Comment by ldicker83** [comment]
Correct, the ordering is different in those UI panels (same with the full-screen UI). This is a user interface issue in terms of consistency, I'll create a new task to make the ordering of resources consistent with the HUD and Breakdown Panel.
