### ISSUE TITLE
Slow incremental recompile for NAS2D changes

### ISSUE THREAD

**Issue by DanRStevens** [ldicker83/OPHD#134]
Within OPHD, 28 out of 63 files contain `#include <NAS2D.h>`. The `<NAS2D.h>` file then includes every header file within the NAS2D library. This means that any small change to any header file within NAS2D will cause those source files in OPHD to be rebuilt. This can be rather slow when testing updates to NAS2D against OPHD.

If those includes were replaced with more specific includes, targeting just the sections of NAS2D that was actually being used, the incremental rebuilds would complete much quicker.

This raises the question, is only `<NAS2D.h>` considered public, or are all header files in the public include folder `include/NAS2D/` considered public? If they are all public, then perhaps we should use more specific includes to allow for faster incremental rebuilds when working in lockstep with NAS2D updates.

Doing so does perhaps increase the public surface area of NAS2D, which could lead to more breaking changes. In particular, if sub header files were included directly, then renaming them would now be a breaking change to downstream projects.

Alternatively, we could have a few topic area includes for the header files. Perhaps a `Renderer.h`, which includes everything in the `Renderer/` folder. That might allow for a few public header files, without being overly specific with all header files.

My though, if the file is in the public include folder, it is effective public, so we should assume other people would use it as such. If we wish to hide a header, while still making it's contents public, we should perhaps move the header into an `internal/` folder, so people know not to use it directly.

----

My recommendation, is to start using more specific header includes, rather than blanket `<NAS2D.h>` includes.

**Comment by ldicker83** [comment]
NAS2D.h is the 'easy way' to include NAS2D features. Basically, it's because I'm lazy. Modeled after SDL, honestly.

I'm not opposed to removing NAS2D and just including the parts that are needed in each downstream module.

**Comment by DanRStevens** [comment]
Ok, perhaps I'll update to more specific includes at some point.

To be fair though, I don't plan to remove `NAS2D.h`. It's still useful as a convenience header to have that. An easy include all, while you're getting things working. Later on, things can be optimized by using more specific headers.

**Comment by ldicker83** [comment]
Fair enough. I'll leave judgement for that up to you.

As a side note, one way to optimize is when including derived headers (e.g., MixerSDL or RendererOpenGL), they include their bases so including the derived is sufficient.

**Comment by DanRStevens** [comment]
That does reduce the number of direct includes that must be maintained, though sadly, that doesn't help compile time, since all referenced code is ultimately included.

----

I find a few interesting ways of analysing the spread of dependencies. The Linux makefile generates dependency information during a build. The dependency files include one line for each include, and traverses them recursively. That can be scanned afterwards to determine how much of the codebase relies on a given file, either directly, or indirectly.

First off, to determine the number of source files (currently 63):
```
find src/ -name '*.cpp' | wc -l
```

The `find` command lists all files (one per line) matching `*.cpp` within the subtree rooted at `src/`. The `wc` (word count) program counts the number of lines (`-l`) of output.

Alternatively, you can count object files, in case you have a mixed language project (.cpp, .c, .asm, etc.). Remember to do a `make clean` first to ensure there are no stale `.o` files to upset the count:
```
find .build/ -name '*.o' | wc -l
```

With that baseline, we can then scan the dependency information to find how many files depend on a particular header file.
```
grep --include='*.d' -rl Common.h .build/ | wc -l
```

Here the `grep` command recursively (`-r`) searches the `.build/` folder for the pattern `Common.h` (can be a regular expression). As this sometimes matches binary `.o` files from the `.build/` folder, the `--include='*.d'` is used to limit the search to dependency files. The `-l` option means print just one line showing the filename when the file contains a match (rather than more detailed line by line matching showing every occurrence). The list of filenames is then piped to `wc -l` to count how many there are.

----

Using the above commands, `Common.h` was included either directly or indirectly by 53 of the 63 translation units. As part of the incremental recompile time improvements, perhaps we might want to look into splitting `Common.h`.

**Comment by DanRStevens** [comment]
To add to the above, it's possible to get a summary for all files.

To get a sense of how widespread a header is used, through both direct and transitive dependencies, we can count how many source files must be recompiled if the header is modified:
```
find src/ -name '*.h' -exec sh -c "grep --include='*.d' -rl \$(basename {}) .build/ | wc -l | tr '\n' ' ' && echo {}" \; | sort -h
```

Example output:
```
1 src/RobotPoolHelper.h
1 src/WindowEventWrapper.h
2 src/GraphWalker.h
2 src/States/PlanetSelectState.h
2 src/States/SplashState.h
2 src/UI/Reports/FactoryReport.h
2 src/UI/Reports/WarehouseReport.h
3 src/States/GameState.h
3 src/States/Planet.h
3 src/UI/FactoryListBox.h
3 src/UI/ProductListBox.h
3 src/UI/Reports/ReportInterface.h
3 src/UI/StructureListBox.h
6 src/StructureTranslator.h
7 src/States/MainMenuState.h
7 src/StructureCatalogue.h
7 src/UI/Core/ListBoxBase.h
8 src/UI/DifficultySelect.h
8 src/UI/MainMenuOptions.h
9 src/Things/Structures/Agridome.h
9 src/Things/Structures/AirShaft.h
9 src/Things/Structures/CargoLander.h
9 src/Things/Structures/CHAP.h
9 src/Things/Structures/ColonistLander.h
9 src/Things/Structures/CommandCenter.h
9 src/Things/Structures/Commercial.h
9 src/Things/Structures/CommTower.h
9 src/Things/Structures/FusionReactor.h
9 src/Things/Structures/Laboratory.h
9 src/Things/Structures/MedicalCenter.h
9 src/Things/Structures/MineShaft.h
9 src/Things/Structures/Nursery.h
9 src/Things/Structures/Park.h
9 src/Things/Structures/Police.h
9 src/Things/Structures/RecreationCenter.h
9 src/Things/Structures/RedLightDistrict.h
9 src/Things/Structures/Residence.h
9 src/Things/Structures/SeedLander.h
9 src/Things/Structures/SeedPower.h
9 src/Things/Structures/SeedSmelter.h
9 src/Things/Structures/Smelter.h
9 src/Things/Structures/SolarPanelArray.h
9 src/Things/Structures/SolarPlant.h
9 src/Things/Structures/StorageTanks.h
9 src/Things/Structures/Structures.h
9 src/Things/Structures/Tube.h
9 src/Things/Structures/University.h
10 src/States/MapViewState.h
10 src/Things/Structures/RobotCommand.h
10 src/Things/Structures/SeedFactory.h
10 src/Things/Structures/SurfaceFactory.h
10 src/Things/Structures/UndergroundFactory.h
10 src/UI/Gui.h
11 src/States/MainReportsUiState.h
11 src/States/MapViewStateHelper.h
11 src/States/Wrapper.h
11 src/UI/DiggerDirection.h
11 src/UI/FactoryProduction.h
11 src/UI/GameOptionsDialog.h
11 src/UI/GameOverDialog.h
11 src/UI/MajorEventAnnouncement.h
11 src/UI/MineOperationsWindow.h
11 src/UI/PopulationPanel.h
11 src/UI/ResourceBreakdownPanel.h
11 src/UI/StructureInspector.h
11 src/UI/TileInspector.h
11 src/UI/WarehouseInspector.h
12 src/RobotPool.h
12 src/Things/Robots/Robodigger.h
12 src/Things/Robots/Robodozer.h
12 src/Things/Robots/Robominer.h
12 src/Things/Robots/Robots.h
12 src/UI/FileIo.h
13 src/Map/TileMap.h
13 src/UI/IconGrid.h
14 src/MicroPather/micropather.h
14 src/StructureManager.h
15 src/Things/Structures/MineFacility.h
15 src/Things/Structures/Warehouse.h
17 src/ProductPool.h
17 src/Templates.h
18 src/ProductionCost.h
18 src/Things/Structures/Factory.h
22 src/Map/Tile.h
24 src/Things/Robots/Robot.h
25 src/Mine.h
25 src/UI/UI.h
26 src/UI/Core/CheckBox.h
26 src/UI/Core/WindowStack.h
27 src/UI/Core/RadioButton.h
27 src/UI/Core/Window.h
28 src/UI/Core/Label.h
29 src/FontManager.h
29 src/UI/Core/ComboBox.h
29 src/UI/Core/TextArea.h
30 src/UI/Core/TextField.h
33 src/Things/Structures/Structure.h
33 src/UI/Core/ListBox.h
34 src/PopulationPool.h
34 src/Things/Thing.h
35 src/ResourcePool.h
35 src/UI/Core/Slider.h
36 src/Population/Morale.h
36 src/Population/Population.h
38 src/UI/Core/Button.h
38 src/UI/Core/UIContainer.h
46 src/UI/Core/Control.h
55 src/Common.h
58 src/Constants/Numbers.h
58 src/Constants/Strings.h
59 src/Constants.h
59 src/Constants/UiConstants.h
```

----

The same analysis can be run for the NAS2D headers, and how widely they impact OPHD:
```
find nas2d-core/include/ -name '*.h' -exec sh -c "grep --include='*.d' -rl \$(basename {}) .build/ | wc -l | tr '\n' ' ' && echo {}" \; | sort -h
```

Example output:
```
0 nas2d-core/include/NAS2D/Documentation.h
0 nas2d-core/include/NAS2D/Renderer/RendererNull.h
0 nas2d-core/include/NAS2D/Resources/FontInfo.h
0 nas2d-core/include/NAS2D/Resources/ImageInfo.h
0 nas2d-core/include/NAS2D/Resources/MusicInfo.h
1 nas2d-core/include/NAS2D/Mixer/MixerNull.h
1 nas2d-core/include/NAS2D/Mixer/MixerSDL.h
1 nas2d-core/include/NAS2D/Renderer/RendererOpenGL.h
34 nas2d-core/include/NAS2D/Exception.h
34 nas2d-core/include/NAS2D/FpsCounter.h
34 nas2d-core/include/NAS2D/Game.h
34 nas2d-core/include/NAS2D/NAS2D.h
34 nas2d-core/include/NAS2D/Resources/Sprite.h
34 nas2d-core/include/NAS2D/StateManager.h
34 nas2d-core/include/NAS2D/Trig.h
34 nas2d-core/include/NAS2D/Version.h
34 nas2d-core/include/NAS2D/Xml/XmlComment.h
34 nas2d-core/include/NAS2D/Xml/XmlDocument.h
34 nas2d-core/include/NAS2D/Xml/Xml.h
34 nas2d-core/include/NAS2D/Xml/XmlHandle.h
34 nas2d-core/include/NAS2D/Xml/XmlMemoryBuffer.h
34 nas2d-core/include/NAS2D/Xml/XmlText.h
34 nas2d-core/include/NAS2D/Xml/XmlUnknown.h
35 nas2d-core/include/NAS2D/File.h
35 nas2d-core/include/NAS2D/Filesystem.h
35 nas2d-core/include/NAS2D/State.h
36 nas2d-core/include/NAS2D/Configuration.h
36 nas2d-core/include/NAS2D/Mixer/Mixer.h
36 nas2d-core/include/NAS2D/Resources/Music.h
36 nas2d-core/include/NAS2D/Resources/Sound.h
39 nas2d-core/include/NAS2D/Xml/XmlAttribute.h
39 nas2d-core/include/NAS2D/Xml/XmlAttributeSet.h
39 nas2d-core/include/NAS2D/Xml/XmlBase.h
39 nas2d-core/include/NAS2D/Xml/XmlElement.h
39 nas2d-core/include/NAS2D/Xml/XmlNode.h
39 nas2d-core/include/NAS2D/Xml/XmlVisitor.h
43 nas2d-core/include/NAS2D/MathUtils.h
50 nas2d-core/include/NAS2D/Timer.h
54 nas2d-core/include/NAS2D/Renderer/DisplayDesc.h
54 nas2d-core/include/NAS2D/Renderer/Renderer.h
55 nas2d-core/include/NAS2D/Common.h
56 nas2d-core/include/NAS2D/EventHandler.h
57 nas2d-core/include/NAS2D/Resources/Font.h
57 nas2d-core/include/NAS2D/StringUtils.h
57 nas2d-core/include/NAS2D/Utility.h
59 nas2d-core/include/NAS2D/Resources/Image.h
59 nas2d-core/include/NAS2D/Resources/Resource.h
61 nas2d-core/include/NAS2D/Delegate.h
61 nas2d-core/include/NAS2D/Signal.h
63 nas2d-core/include/NAS2D/Renderer/Color.h
63 nas2d-core/include/NAS2D/Renderer/Point.h
63 nas2d-core/include/NAS2D/Renderer/Rectangle.h
63 nas2d-core/include/NAS2D/Renderer/Vector.h
```
