### ISSUE TITLE
Add a function to Control that toggles visibility

### ISSUE THREAD

**Issue by cugone** [ldicker83/OPHD#143]
In several places throughout the code the visibility of a control is set to the opposite of whatever it currently is via constructs like: `lstItems.visible(!lstItems.visible());` The exclamation `logical not` operator is sometimes easy to miss. This would be better served as an explicit and highly visible (hah!) single call to `lstItems.toggleVisible();` or `lstItems.toggleVisibility();` that does the toggle internally, i.e., `mVisible = !mVisible;`.

That said, sometimes the new value of a toggle is needed immediately after similar to:
```
lstItem.toggleVisible();
if(lstItem.visible()) {
//...
} else {
//...
}
```
This can be accomplished by returning such a value:
```
//Return the new value
bool Control::toggleVisibile()
{
    mVisible = !mVisible;
    return mVisible;
}
```
and the new code becomes simpler:
```
if(lstItem.toggleVisible()) {
//...
} else {
//...
}
```
If you don't need the new value just let it be discarded by the compiler.

**Comment by ldicker83** [comment]
I don't want to pollute the interface with a call that ultimately serves simply as a convenience function. It is intended to be a clean and simple interface. Toggling is such a simple function that it shouldn't ever really need a convenience function.

That stated, the Control interface could probably use some refactoring.

**Comment by cugone** [comment]
Closing a rejected.
