### ISSUE TITLE
Unable to run from source: No data folder

### ISSUE THREAD

**Issue by cugone** [ldicker83/OPHD#147]
Cloning the repo and then trying to run/debug the game fails immediately because the FileSystem class is looking for the data folder that is not part of the repo.

**Comment by DanRStevens** [comment]
Check the OPHD thread on OPU forums. It contains a link to a zip file with the data folder contents.

The data has not been vetted to be free of copyright restrictions, so it has been left out of the GitHub repositories for now.

**Comment by cugone** [comment]
Where should the data folder be placed? The forum post doesn't explain it, or I can't find where it mentions it.

...Oh cool. Apparently I've had OPU bookmarked for some time and totally forgot.

**Comment by cugone** [comment]
Another thing (probably should be a separate issue), the current master has the FileSystem trying to mount `fonts.dat` and `planets.dat` but none of the data files are packed into zip files.

**Comment by DanRStevens** [comment]
Ahh yes, that's something that needs to be cleaned up.

I think there was a trend towards unpacked data. Having data unpacked reduces the required features for the `Filesystem` class. Less to support if PhysFS is dropped.
