### ISSUE TITLE
Implement Robot Storage and Robot Command Capacity

### ISSUE THREAD

**Issue by ldicker83** [ldicker83/OPHD#5]
With issue #91, we'll be adding storage for items such as robots and so on. Robots are currently manufactured and added to a 'pool' of available robots. This makes sense for having say, 5 total robots before building a Robot Command Center.

**Comment by ldicker83** [comment]
This is now mostly complete -- Goof build the Robot Command Center and added checks for checking robot command capacity.

Now we need to integrate production checks with the factory -- if a factory is producing a robot, enough command capacity must be available otherwise the factory will go into an idle state.

**Comment by Goof-fr** [comment]
In the original game the extra robots were stored in storage.

If you build a new Robot Command Center, the robots are just pulled out of storage to fill the new Robot Command Center.

Maybe a warning at the end of turn to inform that new robots are going to storage could help manage the fact that it could be more useful to build something else.
Or, in the end, it could be a job for a production report to give that kind of information and let the player decide on the actions to take.
