### ISSUE TITLE
Clicking to skip the splash screens at startup can trigger menu button clicks

### ISSUE THREAD

**Issue by Sirbomber** [ldicker83/OPHD#92]
When the game starts up, unless they're disabled through the config file, the player is presented with the Lairworks Entertainment and NAS2D splash screens.  The player can click to skip past these and go directly to the main menu; however the main menu still registers these clicks and if the player's mouse just happens to be positioned over a menu button, that button's callback logic will be executed.  This is especially jarring if the player's mouse happens to be hovering over where the Quit Game button is.

**Comment by ldicker83** [comment]
Confirmed. It's another one of those "The event is still in the queue even though states are changing so the button will react to it inappropriately".

Going to set all buttons to disabled until the fade is complete, should do the trick.
